import type { MatchOptions } from '../game/config'
import type { EndReason } from '../game/simulation'

export interface MatchRecord {
  /** Generated by the client; submitting the same id again returns the stored record. */
  id: string
  playerId: string
  playerName: string
  /** ISO 8601 timestamp. */
  playedAt: string
  score: number
  durationSeconds: number
  endReason: EndReason
  config: MatchOptions
}

export interface RankingEntry extends MatchRecord {
  rank: number
}

export interface Page<T> {
  items: T[]
  page: number
  pageSize: number
  totalItems: number
  totalPages: number
}

export interface PageParams {
  page: number
  pageSize: number
}

/** The ranking only compares matches played with the same options. */
export type RankingParams = PageParams & MatchOptions

export const API = {
  /** GET, with RankingParams as query string, returns Page<RankingEntry>. */
  ranking: '/api/ranking',
  /** POST a MatchRecord, returns it: 201 when created, 200 when it already existed. */
  matches: '/api/matches',
  /** GET, with PageParams as query string, returns Page<MatchRecord>, newest first. */
  playerMatches: (playerId: string) => `/api/players/${playerId}/matches`,
}
